### ISSUE TITLE
Animated timeline problem

### ISSUE THREAD

**Issue by mostindia** [pdir/animated-timeline-bundle#2]
Hello, I use the animated  timeline extension in Contao 4.9.16. I have also installed the Rocksolid theme Tao. 
Unfortunately, the input in animated timeline for multiple images as content slider does not work.
I can select the images in the backend and place them in the article. However, the images are not displayed in the frontend. 
Best regards
Daniel

**Comment by seibtph** [comment]
Hello @mostindia,

have you selected the js_slider template in the layout? If you choose it it should work.

**Comment by mostindia** [comment]
Hello @seibtph,
thank you for help, it's working perfectly
