### ISSUE TITLE
Timeline innerhalb Accordion

### ISSUE THREAD

**Issue by rokawedes** [pdir/animated-timeline-bundle#5]
Hallöchen,

vielen dank für die Timeline-Erweiterung - sehr schön und hilfreich.

Leider bin ich auf die dumme Idee gekommen, die Timeline in ein Accordion zu stopfen, bspw. Timeline für je ein Jahr in ein Accordion-Element. Nun weiß ich, dass das nicht funktionieren kann, weil die Timeline samt Bild-Slider ja ihre Größe berechnen muss, was in einem zugeklappten Accordion-Element nicht funktionieren kann.

Ich kenne die Problematik vom Rocksolid Slider innerhalb Accordions und weiß, wie ich dort den Resize beim Aufklappen anschubse - mit der Timeline bin ich allerdings hilflos.

Könnten Sie mir da weiterhelfen?
Viele Grüße
Ronny

**Comment by seibtph** [comment]
Hallo Ronny,

Ich weiß nicht ob dein Problem noch aktuell ist oder du es bereits lösen konntest. Mit der aktuellsten Version des Animated Timeline sollte das aber bereits funktionieren. Also bitte mal die Version über den Contao Manager aktualisieren. Wenn es nicht klappt, gern nochmal Bescheid geben und den Issue wiedereröffnen.
