### ISSUE TITLE
Fehlermeldung nach Update auf PHP 8

### ISSUE THREAD

**Issue by DhanaKel** [pdir/animated-timeline-bundle#7]
Seit meinem Update auf PHP 8 löst die Erweiterung animated_timeline bei mir einen PHP-Error aus:

**Uncaught PHP Exception Error: "Attempt to assign property "picture" on null" at [...]/vendor/pdir/animated-timeline-bundle/src/Resources/contao/templates/ce_timeline_element.html5 line 20**

Soweit ich das recherchieren konnte, ist das ein bekanntes Problem nach einem Update auf PHP 8 - ich kann es nur nicht eigenständig lösen und bitte deshalb um Hilfe.

**Comment by DhanaKel** [comment]
Ich konnte den Fehler jetzt eingrenzen auf den Content Slider. Wenn ich den Content Slider im Timeline Element nicht nutze, läuft alles einwandfrei.

Wenn ich aber den Content Slider nutzen möchte, gibt es die oben genannte Fehlermeldung und meine Seite wird nicht mehr angezeigt.

**Comment by seibtph** [comment]
Sollte nun in der Version 1.2.1 behoben sein. Bitte die Erweiterung über den Contao Manager aktualisieren.
